//
//  RAMenuItem.h
//  SendToGlass
//
//  Created by Ravel Antunes on 1/31/14.
//  Copyright (c) 2014 Ravel Antunes. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "RAEntityProtocol.h"

#pragma mark - TypeDefs

/*!
 Type of actions.
 */
typedef enum {
    RAActionTypeCustom,
    RAActionTypeReply,
    RAActionTypeReplyAll,
    RAActionTypeDelete,
    RAActionTypeShare,
    RAActionTypeReadAloud,
    RAActionTypeVoiceCall,
    RAActionTypeNavigate,
    RAActionTypeTogglePinned,
    RAActionTypeOpenURI,
    RAActionTypePlayVideo
}RAActionType;


@interface RAMenuItem : NSObject <RAEntityProtocol>


/*!
 The ID for this menu item. This is generated by the application and is treated as an opaque token.
 */
@property (strong, nonatomic) NSString* id;

/*!
 Controls the behavior when the user picks the menu option. Allowed values are defined by RAActionType enum.
 */
@property (nonatomic) RAActionType action;

/*!
 A generic payload whose meaning changes depending on this MenuItem's action.
 - When the action is OPEN_URI, the payload is the URL of the website to view.
 - When the action is PLAY_VIDEO, the payload is the streaming URL of the video
 */
@property (strong, nonatomic) NSString *payload;

@end
